return {
    ["nesw-dark"] = {
        name = "nesw-dark",
        background = "dark",
        ui = {
            bg = "#0a0a0a",
            bg_soft = "#171717",
            bg_muted = "#1d1d1d",
            fg = "#fafafa",
            fg_muted = "#a3a3a3",
            fg_dim = "#737373",
            border = "#262626",
            cursor = "#009fff",
            selection = "#19283c",
            line_highlight = "#19283c",
            line_nr = "#737373",
            line_nr_active = "#a3a3a3",
            indent = "#1d1d1d",
            indent_active = "#262626",
            accent = "#009fff",
        },
        ansi = {
            "#171717",
            "#ff2e3f",
            "#0dbe4e",
            "#ffca00",
            "#009fff",
            "#e130ac",
            "#08c0ef",
            "#bcbcbc",
            "#171717",
            "#ff2e3f",
            "#86c427",
            "#ffca00",
            "#009fff",
            "#e130ac",
            "#08c0ef",
            "#bcbcbc",
        },
        syntax = {
            comment = "#737373",
            string = "#5ecc71",
            number = "#68cdf2",
            constant = "#ffd452",
            keyword = "#ff678d",
            variable = "#ffa359",
            parameter = "#a3a3a3",
            ["function"] = "#9d6afb",
            type = "#d568ea",
            operator = "#636363",
            punctuation = "#636363",
            heading = "#ff855e",
        },
        diagnostic = {
            error = "#ff2e3f",
            warn = "#ffca00",
            info = "#08c0ef",
            hint = "#009fff",
        },
        git = {
            add = "#07c480",
            delete = "#ff2e3f",
            modify = "#009fff",
            conflict = "#7b43f8",
        },
    },
    ["nesw-dark-soft"] = {
        name = "nesw-dark-soft",
        background = "dark",
        ui = {
            bg = "#171717",
            bg_soft = "#101010",
            bg_muted = "#262626",
            fg = "#d4d4d4",
            fg_muted = "#8a8a8a",
            fg_dim = "#636363",
            border = "#1d1d1d",
            cursor = "#69b1ff",
            selection = "#1f3e5e",
            line_highlight = "#1f3e5e",
            line_nr = "#636363",
            line_nr_active = "#8a8a8a",
            indent = "#262626",
            indent_active = "#2c2c2c",
            accent = "#69b1ff",
        },
        ansi = {
            "#171717",
            "#ff2e3f",
            "#0dbe4e",
            "#ffca00",
            "#009fff",
            "#e130ac",
            "#08c0ef",
            "#bcbcbc",
            "#171717",
            "#ff2e3f",
            "#86c427",
            "#ffca00",
            "#009fff",
            "#e130ac",
            "#08c0ef",
            "#bcbcbc",
        },
        syntax = {
            comment = "#636363",
            string = "#8cda94",
            number = "#96d9f6",
            constant = "#ffde80",
            keyword = "#ff91a8",
            variable = "#ffba82",
            parameter = "#8a8a8a",
            ["function"] = "#ba8ffd",
            type = "#e290f0",
            operator = "#737373",
            punctuation = "#737373",
            heading = "#ffa685",
        },
        diagnostic = {
            error = "#ff6762",
            warn = "#ffd452",
            info = "#68cdf2",
            hint = "#69b1ff",
        },
        git = {
            add = "#60d199",
            delete = "#ff6762",
            modify = "#69b1ff",
            conflict = "#9d6afb",
        },
    },
    ["nesw-light"] = {
        name = "nesw-light",
        background = "light",
        ui = {
            bg = "#ffffff",
            bg_soft = "#f5f5f5",
            bg_muted = "#ededed",
            fg = "#0a0a0a",
            fg_muted = "#525252",
            fg_dim = "#737373",
            border = "#e5e5e5",
            cursor = "#009fff",
            selection = "#dfebff",
            line_highlight = "#dfebff",
            line_nr = "#737373",
            line_nr_active = "#525252",
            indent = "#e5e5e5",
            indent_active = "#d4d4d4",
            accent = "#009fff",
        },
        ansi = {
            "#1d1d1d",
            "#d52c36",
            "#18a46c",
            "#d5a910",
            "#1a85d4",
            "#bd2e90",
            "#1ca1c7",
            "#bcbcbc",
            "#1d1d1d",
            "#d52c36",
            "#77a42a",
            "#d5a910",
            "#1a85d4",
            "#bd2e90",
            "#1ca1c7",
            "#bcbcbc",
        },
        syntax = {
            comment = "#737373",
            string = "#199f43",
            number = "#1ca1c7",
            constant = "#d5a910",
            keyword = "#d32a61",
            variable = "#d47628",
            parameter = "#636363",
            ["function"] = "#693acf",
            type = "#a631be",
            operator = "#636363",
            punctuation = "#636363",
            heading = "#d5512f",
        },
        diagnostic = {
            error = "#d52c36",
            warn = "#d5a910",
            info = "#1ca1c7",
            hint = "#009fff",
        },
        git = {
            add = "#18a46c",
            delete = "#d52c36",
            modify = "#009fff",
            conflict = "#693acf",
        },
    },
    ["nesw-light-soft"] = {
        name = "nesw-light-soft",
        background = "light",
        ui = {
            bg = "#ffffff",
            bg_soft = "#f7f7f7",
            bg_muted = "#f5f5f5",
            fg = "#525252",
            fg_muted = "#737373",
            fg_dim = "#8a8a8a",
            border = "#ededed",
            cursor = "#009fff",
            selection = "#dfebff",
            line_highlight = "#dfebff",
            line_nr = "#8a8a8a",
            line_nr_active = "#737373",
            indent = "#ededed",
            indent_active = "#e5e5e5",
            accent = "#009fff",
        },
        ansi = {
            "#1d1d1d",
            "#ff2e3f",
            "#0dbe4e",
            "#ffca00",
            "#009fff",
            "#e130ac",
            "#08c0ef",
            "#bcbcbc",
            "#1d1d1d",
            "#ff2e3f",
            "#86c427",
            "#ffca00",
            "#009fff",
            "#e130ac",
            "#08c0ef",
            "#bcbcbc",
        },
        syntax = {
            comment = "#8a8a8a",
            string = "#0dbe4e",
            number = "#08c0ef",
            constant = "#ffca00",
            keyword = "#ff678d",
            variable = "#fe8c2c",
            parameter = "#737373",
            ["function"] = "#9d6afb",
            type = "#d568ea",
            operator = "#737373",
            punctuation = "#737373",
            heading = "#ff5d36",
        },
        diagnostic = {
            error = "#ff2e3f",
            warn = "#ffca00",
            info = "#08c0ef",
            hint = "#009fff",
        },
        git = {
            add = "#07c480",
            delete = "#ff2e3f",
            modify = "#009fff",
            conflict = "#7b43f8",
        },
    },
}
